// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idibtxvvijdnzprtybju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkaWJ0eHZ2aWpkbnpwcnR5Ymp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjk3MTYsImV4cCI6MjA2MTk0NTcxNn0.nY-Gz8P70lNbjOhqJfD_YUEXLDUxNMWK56A8JLtOdlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);